// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/exsync/exsync.proto

/*
Package exsync is a generated protocol buffer package.

It is generated from these files:
	proto/exsync/exsync.proto

It has these top-level messages:
	ReqPing
	Pong
	Req
	ReqTrades
	ReqOrders
	RespIndex
	RespOrders
	RespTrades
	Timestamp
	Order
	Trade
	RespDepth
	Balance
	Position
	RespPosition
	RespBalance
*/
package exsync

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TradeAction int32

const (
	TradeAction_OpenLong   TradeAction = 0
	TradeAction_OpenShort  TradeAction = 1
	TradeAction_CloseLong  TradeAction = 2
	TradeAction_CloseShort TradeAction = 3
	TradeAction_Buy        TradeAction = 4
	TradeAction_Sell       TradeAction = 5
)

var TradeAction_name = map[int32]string{
	0: "OpenLong",
	1: "OpenShort",
	2: "CloseLong",
	3: "CloseShort",
	4: "Buy",
	5: "Sell",
}
var TradeAction_value = map[string]int32{
	"OpenLong":   0,
	"OpenShort":  1,
	"CloseLong":  2,
	"CloseShort": 3,
	"Buy":        4,
	"Sell":       5,
}

func (x TradeAction) String() string {
	return proto.EnumName(TradeAction_name, int32(x))
}
func (TradeAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PositionType int32

const (
	PositionType_Long  PositionType = 0
	PositionType_Short PositionType = 1
)

var PositionType_name = map[int32]string{
	0: "Long",
	1: "Short",
}
var PositionType_value = map[string]int32{
	"Long":  0,
	"Short": 1,
}

func (x PositionType) String() string {
	return proto.EnumName(PositionType_name, int32(x))
}
func (PositionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CurrencyUnit int32

const (
	CurrencyUnit_CNY CurrencyUnit = 0
	CurrencyUnit_USD CurrencyUnit = 1
	CurrencyUnit_BTC CurrencyUnit = 2
	CurrencyUnit_LTC CurrencyUnit = 3
)

var CurrencyUnit_name = map[int32]string{
	0: "CNY",
	1: "USD",
	2: "BTC",
	3: "LTC",
}
var CurrencyUnit_value = map[string]int32{
	"CNY": 0,
	"USD": 1,
	"BTC": 2,
	"LTC": 3,
}

func (x CurrencyUnit) String() string {
	return proto.EnumName(CurrencyUnit_name, int32(x))
}
func (CurrencyUnit) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type OrderStatus int32

const (
	OrderStatus_OrderStatusCreated   OrderStatus = 0
	OrderStatus_OrderStatusPartial   OrderStatus = 1
	OrderStatus_OrderStatusComplete  OrderStatus = 2
	OrderStatus_OrderStatusCanceled  OrderStatus = 3
	OrderStatus_OrderStatusCanceling OrderStatus = 4
)

var OrderStatus_name = map[int32]string{
	0: "OrderStatusCreated",
	1: "OrderStatusPartial",
	2: "OrderStatusComplete",
	3: "OrderStatusCanceled",
	4: "OrderStatusCanceling",
}
var OrderStatus_value = map[string]int32{
	"OrderStatusCreated":   0,
	"OrderStatusPartial":   1,
	"OrderStatusComplete":  2,
	"OrderStatusCanceled":  3,
	"OrderStatusCanceling": 4,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}
func (OrderStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ReqPing struct {
}

func (m *ReqPing) Reset()                    { *m = ReqPing{} }
func (m *ReqPing) String() string            { return proto.CompactTextString(m) }
func (*ReqPing) ProtoMessage()               {}
func (*ReqPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Pong struct {
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Req struct {
	Exname string `protobuf:"bytes,1,opt,name=exname" json:"exname,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Req) GetExname() string {
	if m != nil {
		return m.Exname
	}
	return ""
}

type ReqTrades struct {
	Exname string `protobuf:"bytes,1,opt,name=exname" json:"exname,omitempty"`
	Since  string `protobuf:"bytes,2,opt,name=since" json:"since,omitempty"`
	Num    int32  `protobuf:"varint,3,opt,name=num" json:"num,omitempty"`
}

func (m *ReqTrades) Reset()                    { *m = ReqTrades{} }
func (m *ReqTrades) String() string            { return proto.CompactTextString(m) }
func (*ReqTrades) ProtoMessage()               {}
func (*ReqTrades) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReqTrades) GetExname() string {
	if m != nil {
		return m.Exname
	}
	return ""
}

func (m *ReqTrades) GetSince() string {
	if m != nil {
		return m.Since
	}
	return ""
}

func (m *ReqTrades) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type ReqOrders struct {
	Exname string   `protobuf:"bytes,1,opt,name=exname" json:"exname,omitempty"`
	Ids    []string `protobuf:"bytes,2,rep,name=ids" json:"ids,omitempty"`
}

func (m *ReqOrders) Reset()                    { *m = ReqOrders{} }
func (m *ReqOrders) String() string            { return proto.CompactTextString(m) }
func (*ReqOrders) ProtoMessage()               {}
func (*ReqOrders) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReqOrders) GetExname() string {
	if m != nil {
		return m.Exname
	}
	return ""
}

func (m *ReqOrders) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type RespIndex struct {
	Index float64 `protobuf:"fixed64,1,opt,name=index" json:"index,omitempty"`
}

func (m *RespIndex) Reset()                    { *m = RespIndex{} }
func (m *RespIndex) String() string            { return proto.CompactTextString(m) }
func (*RespIndex) ProtoMessage()               {}
func (*RespIndex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RespIndex) GetIndex() float64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type RespOrders struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *RespOrders) Reset()                    { *m = RespOrders{} }
func (m *RespOrders) String() string            { return proto.CompactTextString(m) }
func (*RespOrders) ProtoMessage()               {}
func (*RespOrders) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RespOrders) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type RespTrades struct {
	Trades []*Trade `protobuf:"bytes,1,rep,name=trades" json:"trades,omitempty"`
}

func (m *RespTrades) Reset()                    { *m = RespTrades{} }
func (m *RespTrades) String() string            { return proto.CompactTextString(m) }
func (*RespTrades) ProtoMessage()               {}
func (*RespTrades) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RespTrades) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

type Timestamp struct {
	Seconds int64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	Nanos   int64 `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Timestamp) GetSeconds() int64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func (m *Timestamp) GetNanos() int64 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

type Order struct {
	Id         string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TAction    TradeAction `protobuf:"varint,2,opt,name=tAction,enum=exsync.TradeAction" json:"tAction,omitempty"`
	Amount     float64     `protobuf:"fixed64,3,opt,name=amount" json:"amount,omitempty"`
	Price      float64     `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	DealAmount float64     `protobuf:"fixed64,5,opt,name=dealAmount" json:"dealAmount,omitempty"`
	DealMoney  float64     `protobuf:"fixed64,6,opt,name=dealMoney" json:"dealMoney,omitempty"`
	AvgPrice   float64     `protobuf:"fixed64,7,opt,name=avgPrice" json:"avgPrice,omitempty"`
	Fee        float64     `protobuf:"fixed64,8,opt,name=fee" json:"fee,omitempty"`
	Status     OrderStatus `protobuf:"varint,9,opt,name=status,enum=exsync.OrderStatus" json:"status,omitempty"`
	CreateTime *Timestamp  `protobuf:"bytes,10,opt,name=createTime" json:"createTime,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetTAction() TradeAction {
	if m != nil {
		return m.TAction
	}
	return TradeAction_OpenLong
}

func (m *Order) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetDealAmount() float64 {
	if m != nil {
		return m.DealAmount
	}
	return 0
}

func (m *Order) GetDealMoney() float64 {
	if m != nil {
		return m.DealMoney
	}
	return 0
}

func (m *Order) GetAvgPrice() float64 {
	if m != nil {
		return m.AvgPrice
	}
	return 0
}

func (m *Order) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Order) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_OrderStatusCreated
}

func (m *Order) GetCreateTime() *Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type Trade struct {
	Id         string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TAction    TradeAction `protobuf:"varint,2,opt,name=tAction,enum=exsync.TradeAction" json:"tAction,omitempty"`
	Amount     float64     `protobuf:"fixed64,3,opt,name=amount" json:"amount,omitempty"`
	Price      float64     `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	Fee        float64     `protobuf:"fixed64,5,opt,name=fee" json:"fee,omitempty"`
	CreateTime *Timestamp  `protobuf:"bytes,6,opt,name=createTime" json:"createTime,omitempty"`
}

func (m *Trade) Reset()                    { *m = Trade{} }
func (m *Trade) String() string            { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()               {}
func (*Trade) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Trade) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Trade) GetTAction() TradeAction {
	if m != nil {
		return m.TAction
	}
	return TradeAction_OpenLong
}

func (m *Trade) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Trade) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetFee() float64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Trade) GetCreateTime() *Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type RespDepth struct {
	Asks []*Trade `protobuf:"bytes,1,rep,name=asks" json:"asks,omitempty"`
	Bids []*Trade `protobuf:"bytes,2,rep,name=bids" json:"bids,omitempty"`
}

func (m *RespDepth) Reset()                    { *m = RespDepth{} }
func (m *RespDepth) String() string            { return proto.CompactTextString(m) }
func (*RespDepth) ProtoMessage()               {}
func (*RespDepth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RespDepth) GetAsks() []*Trade {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *RespDepth) GetBids() []*Trade {
	if m != nil {
		return m.Bids
	}
	return nil
}

type Balance struct {
	Amount       float64      `protobuf:"fixed64,1,opt,name=amount" json:"amount,omitempty"`
	Deposit      float64      `protobuf:"fixed64,2,opt,name=deposit" json:"deposit,omitempty"`
	RealProfil   float64      `protobuf:"fixed64,3,opt,name=realProfil" json:"realProfil,omitempty"`
	UnrealProfit float64      `protobuf:"fixed64,4,opt,name=UnrealProfit,json=unrealProfit" json:"UnrealProfit,omitempty"`
	RiskRate     float64      `protobuf:"fixed64,5,opt,name=RiskRate,json=riskRate" json:"RiskRate,omitempty"`
	Currentcy    CurrencyUnit `protobuf:"varint,6,opt,name=currentcy,enum=exsync.CurrencyUnit" json:"currentcy,omitempty"`
}

func (m *Balance) Reset()                    { *m = Balance{} }
func (m *Balance) String() string            { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()               {}
func (*Balance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Balance) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Balance) GetDeposit() float64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *Balance) GetRealProfil() float64 {
	if m != nil {
		return m.RealProfil
	}
	return 0
}

func (m *Balance) GetUnrealProfit() float64 {
	if m != nil {
		return m.UnrealProfit
	}
	return 0
}

func (m *Balance) GetRiskRate() float64 {
	if m != nil {
		return m.RiskRate
	}
	return 0
}

func (m *Balance) GetCurrentcy() CurrencyUnit {
	if m != nil {
		return m.Currentcy
	}
	return CurrencyUnit_CNY
}

type Position struct {
	Id              string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Ptype           PositionType `protobuf:"varint,2,opt,name=ptype,enum=exsync.PositionType" json:"ptype,omitempty"`
	Amount          float64      `protobuf:"fixed64,3,opt,name=amount" json:"amount,omitempty"`
	AvailableAmount float64      `protobuf:"fixed64,4,opt,name=availableAmount" json:"availableAmount,omitempty"`
	AvgPrice        float64      `protobuf:"fixed64,5,opt,name=avgPrice" json:"avgPrice,omitempty"`
	Money           float64      `protobuf:"fixed64,6,opt,name=money" json:"money,omitempty"`
	Deposti         float64      `protobuf:"fixed64,7,opt,name=deposti" json:"deposti,omitempty"`
	Leverge         float64      `protobuf:"fixed64,8,opt,name=leverge" json:"leverge,omitempty"`
	ForceClosePrice float64      `protobuf:"fixed64,9,opt,name=forceClosePrice" json:"forceClosePrice,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Position) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Position) GetPtype() PositionType {
	if m != nil {
		return m.Ptype
	}
	return PositionType_Long
}

func (m *Position) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Position) GetAvailableAmount() float64 {
	if m != nil {
		return m.AvailableAmount
	}
	return 0
}

func (m *Position) GetAvgPrice() float64 {
	if m != nil {
		return m.AvgPrice
	}
	return 0
}

func (m *Position) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *Position) GetDeposti() float64 {
	if m != nil {
		return m.Deposti
	}
	return 0
}

func (m *Position) GetLeverge() float64 {
	if m != nil {
		return m.Leverge
	}
	return 0
}

func (m *Position) GetForceClosePrice() float64 {
	if m != nil {
		return m.ForceClosePrice
	}
	return 0
}

type RespPosition struct {
	Long  *Position `protobuf:"bytes,1,opt,name=long" json:"long,omitempty"`
	Short *Position `protobuf:"bytes,2,opt,name=short" json:"short,omitempty"`
}

func (m *RespPosition) Reset()                    { *m = RespPosition{} }
func (m *RespPosition) String() string            { return proto.CompactTextString(m) }
func (*RespPosition) ProtoMessage()               {}
func (*RespPosition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RespPosition) GetLong() *Position {
	if m != nil {
		return m.Long
	}
	return nil
}

func (m *RespPosition) GetShort() *Position {
	if m != nil {
		return m.Short
	}
	return nil
}

type RespBalance struct {
	Balance *Balance `protobuf:"bytes,1,opt,name=balance" json:"balance,omitempty"`
}

func (m *RespBalance) Reset()                    { *m = RespBalance{} }
func (m *RespBalance) String() string            { return proto.CompactTextString(m) }
func (*RespBalance) ProtoMessage()               {}
func (*RespBalance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RespBalance) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqPing)(nil), "exsync.ReqPing")
	proto.RegisterType((*Pong)(nil), "exsync.Pong")
	proto.RegisterType((*Req)(nil), "exsync.Req")
	proto.RegisterType((*ReqTrades)(nil), "exsync.ReqTrades")
	proto.RegisterType((*ReqOrders)(nil), "exsync.ReqOrders")
	proto.RegisterType((*RespIndex)(nil), "exsync.RespIndex")
	proto.RegisterType((*RespOrders)(nil), "exsync.RespOrders")
	proto.RegisterType((*RespTrades)(nil), "exsync.RespTrades")
	proto.RegisterType((*Timestamp)(nil), "exsync.Timestamp")
	proto.RegisterType((*Order)(nil), "exsync.Order")
	proto.RegisterType((*Trade)(nil), "exsync.Trade")
	proto.RegisterType((*RespDepth)(nil), "exsync.RespDepth")
	proto.RegisterType((*Balance)(nil), "exsync.Balance")
	proto.RegisterType((*Position)(nil), "exsync.Position")
	proto.RegisterType((*RespPosition)(nil), "exsync.RespPosition")
	proto.RegisterType((*RespBalance)(nil), "exsync.RespBalance")
	proto.RegisterEnum("exsync.TradeAction", TradeAction_name, TradeAction_value)
	proto.RegisterEnum("exsync.PositionType", PositionType_name, PositionType_value)
	proto.RegisterEnum("exsync.CurrencyUnit", CurrencyUnit_name, CurrencyUnit_value)
	proto.RegisterEnum("exsync.OrderStatus", OrderStatus_name, OrderStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SyncService service

type SyncServiceClient interface {
	Ping(ctx context.Context, in *ReqPing, opts ...grpc.CallOption) (*Pong, error)
	GetOrders(ctx context.Context, in *ReqOrders, opts ...grpc.CallOption) (*RespOrders, error)
	GetTrades(ctx context.Context, in *ReqTrades, opts ...grpc.CallOption) (*RespTrades, error)
	GetDepth(ctx context.Context, in *Req, opts ...grpc.CallOption) (*RespDepth, error)
	GetIndex(ctx context.Context, in *Req, opts ...grpc.CallOption) (*RespIndex, error)
	GetPosition(ctx context.Context, in *Req, opts ...grpc.CallOption) (*RespPosition, error)
	GetBalance(ctx context.Context, in *Req, opts ...grpc.CallOption) (*RespBalance, error)
}

type syncServiceClient struct {
	cc *grpc.ClientConn
}

func NewSyncServiceClient(cc *grpc.ClientConn) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) Ping(ctx context.Context, in *ReqPing, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := grpc.Invoke(ctx, "/exsync.SyncService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetOrders(ctx context.Context, in *ReqOrders, opts ...grpc.CallOption) (*RespOrders, error) {
	out := new(RespOrders)
	err := grpc.Invoke(ctx, "/exsync.SyncService/GetOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetTrades(ctx context.Context, in *ReqTrades, opts ...grpc.CallOption) (*RespTrades, error) {
	out := new(RespTrades)
	err := grpc.Invoke(ctx, "/exsync.SyncService/GetTrades", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetDepth(ctx context.Context, in *Req, opts ...grpc.CallOption) (*RespDepth, error) {
	out := new(RespDepth)
	err := grpc.Invoke(ctx, "/exsync.SyncService/GetDepth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetIndex(ctx context.Context, in *Req, opts ...grpc.CallOption) (*RespIndex, error) {
	out := new(RespIndex)
	err := grpc.Invoke(ctx, "/exsync.SyncService/GetIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetPosition(ctx context.Context, in *Req, opts ...grpc.CallOption) (*RespPosition, error) {
	out := new(RespPosition)
	err := grpc.Invoke(ctx, "/exsync.SyncService/GetPosition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncServiceClient) GetBalance(ctx context.Context, in *Req, opts ...grpc.CallOption) (*RespBalance, error) {
	out := new(RespBalance)
	err := grpc.Invoke(ctx, "/exsync.SyncService/GetBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SyncService service

type SyncServiceServer interface {
	Ping(context.Context, *ReqPing) (*Pong, error)
	GetOrders(context.Context, *ReqOrders) (*RespOrders, error)
	GetTrades(context.Context, *ReqTrades) (*RespTrades, error)
	GetDepth(context.Context, *Req) (*RespDepth, error)
	GetIndex(context.Context, *Req) (*RespIndex, error)
	GetPosition(context.Context, *Req) (*RespPosition, error)
	GetBalance(context.Context, *Req) (*RespBalance, error)
}

func RegisterSyncServiceServer(s *grpc.Server, srv SyncServiceServer) {
	s.RegisterService(&_SyncService_serviceDesc, srv)
}

func _SyncService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqPing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exsync.SyncService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).Ping(ctx, req.(*ReqPing))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqOrders)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exsync.SyncService/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetOrders(ctx, req.(*ReqOrders))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTrades)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exsync.SyncService/GetTrades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetTrades(ctx, req.(*ReqTrades))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetDepth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetDepth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exsync.SyncService/GetDepth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetDepth(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exsync.SyncService/GetIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetIndex(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exsync.SyncService/GetPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetPosition(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exsync.SyncService/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServiceServer).GetBalance(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _SyncService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "exsync.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SyncService_Ping_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _SyncService_GetOrders_Handler,
		},
		{
			MethodName: "GetTrades",
			Handler:    _SyncService_GetTrades_Handler,
		},
		{
			MethodName: "GetDepth",
			Handler:    _SyncService_GetDepth_Handler,
		},
		{
			MethodName: "GetIndex",
			Handler:    _SyncService_GetIndex_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _SyncService_GetPosition_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _SyncService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/exsync/exsync.proto",
}

func init() { proto.RegisterFile("proto/exsync/exsync.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 985 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x8e, 0xed, 0x38, 0x89, 0x4f, 0xd2, 0xad, 0x77, 0x36, 0x2a, 0x66, 0x05, 0x28, 0x1d, 0x28,
	0x84, 0x00, 0x05, 0x52, 0x90, 0x90, 0xb8, 0x6a, 0x53, 0x69, 0x85, 0x28, 0x34, 0x4c, 0xb2, 0x17,
	0x48, 0xbd, 0xf1, 0xda, 0x67, 0x53, 0xab, 0xce, 0xd8, 0x6b, 0x4f, 0x56, 0x9b, 0x47, 0xe0, 0x0d,
	0x78, 0x15, 0xee, 0x78, 0x03, 0x5e, 0x82, 0x07, 0x41, 0xf3, 0x63, 0xc7, 0x49, 0x89, 0xc4, 0x15,
	0x57, 0x3b, 0xdf, 0xf9, 0xbe, 0x73, 0x3c, 0xe7, 0x9b, 0x33, 0x99, 0x85, 0x77, 0xf3, 0x22, 0x13,
	0xd9, 0x97, 0x78, 0x57, 0x6e, 0x79, 0x64, 0xfe, 0x3c, 0x56, 0x31, 0xd2, 0xd1, 0x88, 0x7a, 0xd0,
	0x65, 0x78, 0x33, 0x4f, 0xf8, 0x8a, 0x76, 0xa0, 0x3d, 0xcf, 0xf8, 0x8a, 0xbe, 0x0f, 0x0e, 0xc3,
	0x1b, 0xf2, 0x00, 0x3a, 0x78, 0xc7, 0xc3, 0x35, 0x06, 0xd6, 0xc8, 0x1a, 0x7b, 0xcc, 0x20, 0xfa,
	0x23, 0x78, 0x0c, 0x6f, 0x96, 0x45, 0x18, 0x63, 0x79, 0x4c, 0x44, 0x86, 0xe0, 0x96, 0x09, 0x8f,
	0x30, 0xb0, 0x55, 0x58, 0x03, 0xe2, 0x83, 0xc3, 0x37, 0xeb, 0xc0, 0x19, 0x59, 0x63, 0x97, 0xc9,
	0x25, 0xfd, 0x56, 0x15, 0x7b, 0x59, 0xc4, 0x58, 0x1c, 0x2f, 0xe6, 0x83, 0x93, 0xc4, 0x65, 0x60,
	0x8f, 0x9c, 0xb1, 0xc7, 0xe4, 0x92, 0x3e, 0x94, 0x69, 0x65, 0xfe, 0x03, 0x8f, 0xf1, 0x4e, 0x7e,
	0x2b, 0x91, 0x0b, 0x95, 0x65, 0x31, 0x0d, 0xe8, 0x13, 0x00, 0x29, 0x31, 0xa5, 0x1f, 0x41, 0x27,
	0x53, 0xab, 0xc0, 0x1a, 0x39, 0xe3, 0xfe, 0xf4, 0xde, 0x63, 0xe3, 0x86, 0xe2, 0x99, 0x21, 0xab,
	0x24, 0xd3, 0xdc, 0x23, 0xe8, 0x08, 0xb5, 0x3a, 0x4c, 0x52, 0x3c, 0x33, 0x24, 0xfd, 0x1e, 0xbc,
	0x65, 0xb2, 0xc6, 0x52, 0x84, 0xeb, 0x9c, 0x04, 0xd0, 0x2d, 0x31, 0xca, 0x78, 0x5c, 0xaa, 0xed,
	0x38, 0xac, 0x82, 0x72, 0x9b, 0x3c, 0xe4, 0x59, 0xa9, 0x2c, 0x71, 0x98, 0x06, 0xf4, 0x4f, 0x1b,
	0x5c, 0xb5, 0x07, 0x72, 0x02, 0x76, 0x12, 0x9b, 0xce, 0xed, 0x24, 0x26, 0x5f, 0x40, 0x57, 0x3c,
	0x8d, 0x44, 0x92, 0x71, 0x95, 0x71, 0x32, 0x3d, 0xdb, 0xfb, 0xbc, 0xa6, 0x58, 0xa5, 0x91, 0xe6,
	0x85, 0xeb, 0x6c, 0xc3, 0x85, 0xb2, 0xd7, 0x62, 0x06, 0xc9, 0xcf, 0xe6, 0x45, 0x12, 0x61, 0xd0,
	0xd6, 0xee, 0x28, 0x40, 0x3e, 0x00, 0x88, 0x31, 0x4c, 0x9f, 0xea, 0x0c, 0x57, 0x51, 0x8d, 0x08,
	0x79, 0x0f, 0x3c, 0x89, 0x7e, 0xca, 0x38, 0x6e, 0x83, 0x8e, 0xa2, 0x77, 0x01, 0x72, 0x0e, 0xbd,
	0xf0, 0x76, 0x35, 0x57, 0x65, 0xbb, 0x8a, 0xac, 0xb1, 0x3c, 0xac, 0x6b, 0xc4, 0xa0, 0xa7, 0xc2,
	0x72, 0x49, 0x3e, 0x83, 0x4e, 0x29, 0x42, 0xb1, 0x29, 0x03, 0x6f, 0xbf, 0x0f, 0xd5, 0xf7, 0x42,
	0x51, 0xcc, 0x48, 0xc8, 0xd7, 0x00, 0x51, 0x81, 0xa1, 0x40, 0x69, 0x69, 0x00, 0x23, 0x6b, 0xdc,
	0x9f, 0x9e, 0xd6, 0x8d, 0x57, 0x36, 0xb3, 0x86, 0x88, 0xfe, 0x61, 0x81, 0xab, 0x2c, 0xf9, 0x7f,
	0x2d, 0x34, 0x8d, 0xba, 0xbb, 0x46, 0xf7, 0xf7, 0xde, 0xf9, 0x2f, 0x7b, 0xff, 0x45, 0x0f, 0xf2,
	0x73, 0xcc, 0xc5, 0x6b, 0xf2, 0x10, 0xda, 0x61, 0xf9, 0xe6, 0xc8, 0xb4, 0x29, 0x4a, 0x4a, 0xae,
	0xaa, 0xbb, 0xf0, 0xb6, 0x44, 0x52, 0xf4, 0x2f, 0x0b, 0xba, 0xcf, 0xc2, 0x34, 0x94, 0x17, 0x6e,
	0xd7, 0x91, 0xb5, 0xd7, 0x51, 0x00, 0xdd, 0x18, 0xf3, 0xac, 0x4c, 0x84, 0x32, 0xc6, 0x62, 0x15,
	0x94, 0x83, 0x51, 0x60, 0x98, 0xce, 0x8b, 0xec, 0x3a, 0x49, 0x8d, 0x0f, 0x8d, 0x08, 0xa1, 0x30,
	0xb8, 0xe4, 0x35, 0x16, 0xc6, 0x92, 0xc1, 0xa6, 0x11, 0x93, 0xe3, 0xc1, 0x92, 0xf2, 0x0d, 0x0b,
	0x45, 0x65, 0x4f, 0xaf, 0x30, 0x98, 0x4c, 0xc1, 0x8b, 0x36, 0x45, 0x81, 0x5c, 0x44, 0x7a, 0xb0,
	0x4e, 0xa6, 0xc3, 0xaa, 0x8b, 0x99, 0x22, 0xa2, 0xed, 0x25, 0x4f, 0x04, 0xdb, 0xc9, 0xe8, 0xef,
	0x36, 0xf4, 0xe6, 0x72, 0x77, 0xf2, 0x90, 0x0e, 0xcf, 0x78, 0x02, 0x6e, 0x2e, 0xb6, 0x39, 0x9a,
	0x13, 0xae, 0x8b, 0x55, 0x09, 0xcb, 0x6d, 0x8e, 0x4c, 0x4b, 0x8e, 0x1e, 0xf0, 0x18, 0xee, 0x87,
	0xb7, 0x61, 0x92, 0x86, 0x57, 0x29, 0x9a, 0x2b, 0xa1, 0xfb, 0x3a, 0x0c, 0xef, 0x4d, 0xbe, 0x7b,
	0x30, 0xf9, 0x43, 0x70, 0xd7, 0x8d, 0xfb, 0xa2, 0x41, 0x6d, 0xb5, 0x48, 0xcc, 0x55, 0xa9, 0xa0,
	0x64, 0x52, 0xbc, 0xc5, 0x62, 0x55, 0xdd, 0x96, 0x0a, 0xca, 0xfd, 0x5c, 0x67, 0x45, 0x84, 0xb3,
	0x34, 0x2b, 0x51, 0x7f, 0xcc, 0xd3, 0xfb, 0x39, 0x08, 0xd3, 0x57, 0x30, 0x90, 0xf3, 0x53, 0xbb,
	0xf3, 0x11, 0xb4, 0xd3, 0x8c, 0xaf, 0x94, 0x3f, 0xfd, 0xa9, 0x7f, 0x68, 0x06, 0x53, 0x2c, 0xf9,
	0x18, 0xdc, 0xf2, 0x75, 0x56, 0xe8, 0xc3, 0xff, 0x37, 0x99, 0xa6, 0xe9, 0x77, 0xd0, 0x97, 0xd5,
	0xab, 0x69, 0xfa, 0x14, 0xba, 0x57, 0x7a, 0x69, 0xea, 0xdf, 0xaf, 0x12, 0x8d, 0x82, 0x55, 0xfc,
	0xe4, 0x15, 0xf4, 0x1b, 0x57, 0x8c, 0x0c, 0xa0, 0xf7, 0x32, 0x47, 0xfe, 0x22, 0xe3, 0x2b, 0xbf,
	0x45, 0xee, 0x81, 0x27, 0xd1, 0x42, 0x7e, 0xc3, 0xb7, 0x24, 0x54, 0x1d, 0x29, 0xd6, 0x26, 0x27,
	0x00, 0x0a, 0x6a, 0xda, 0x21, 0x5d, 0x70, 0x9e, 0x6d, 0xb6, 0x7e, 0x9b, 0xf4, 0xa0, 0xbd, 0xc0,
	0x34, 0xf5, 0xdd, 0xc9, 0x87, 0x30, 0x68, 0x1e, 0xaf, 0x64, 0x4c, 0x69, 0x0f, 0x5c, 0x53, 0x76,
	0x32, 0x85, 0x41, 0x73, 0xa0, 0x64, 0x9d, 0xd9, 0xcf, 0xbf, 0xfa, 0x2d, 0xb9, 0xb8, 0x5c, 0x3c,
	0xf7, 0x2d, 0x55, 0x79, 0x39, 0xf3, 0x6d, 0xb9, 0x78, 0xb1, 0x9c, 0xf9, 0xce, 0xe4, 0x37, 0x0b,
	0xfa, 0x8d, 0x5f, 0x25, 0xf2, 0x00, 0x48, 0x03, 0xce, 0xd4, 0xbd, 0x8d, 0xfd, 0xd6, 0x41, 0x7c,
	0x1e, 0x16, 0x22, 0x09, 0x53, 0xdf, 0x22, 0xef, 0xc0, 0x59, 0x53, 0x9f, 0xad, 0xf3, 0x14, 0x05,
	0xfa, 0xf6, 0x21, 0x21, 0x3d, 0x4a, 0x31, 0xf6, 0x1d, 0x12, 0xc0, 0xf0, 0x2d, 0x22, 0xe1, 0x2b,
	0xbf, 0x3d, 0xfd, 0xdb, 0x86, 0xfe, 0x62, 0xcb, 0xa3, 0x05, 0x16, 0xb7, 0x72, 0xbc, 0x3e, 0x81,
	0xb6, 0x7c, 0xa6, 0x49, 0x6d, 0xba, 0x79, 0xb7, 0xcf, 0x07, 0xbb, 0xe3, 0xe3, 0x2b, 0xda, 0x22,
	0xdf, 0x80, 0x77, 0x81, 0xc2, 0x3c, 0x7c, 0xa7, 0x0d, 0xb5, 0x0e, 0x9d, 0x93, 0x5d, 0xa8, 0x7a,
	0x1f, 0xeb, 0x2c, 0xf3, 0xf2, 0x35, 0xb3, 0x74, 0x68, 0x3f, 0x4b, 0xc7, 0x68, 0x8b, 0x7c, 0x0e,
	0xbd, 0x0b, 0x14, 0xfa, 0xe7, 0xab, 0xdf, 0x48, 0x3a, 0x3f, 0x6d, 0xca, 0x15, 0x5f, 0xab, 0xf5,
	0xab, 0x7d, 0x5c, 0xad, 0x78, 0xda, 0x22, 0x53, 0xe8, 0x5f, 0xa0, 0xa8, 0x47, 0x7b, 0x2f, 0x61,
	0xd8, 0x4c, 0xa8, 0x24, 0xb4, 0x45, 0xbe, 0x02, 0xb8, 0x40, 0x51, 0x0d, 0xec, 0x5e, 0xca, 0x59,
	0x33, 0xc5, 0x28, 0x68, 0xeb, 0xaa, 0xa3, 0xfe, 0x1f, 0x7a, 0xf2, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd9, 0x4a, 0xa2, 0x32, 0x2c, 0x09, 0x00, 0x00,
}
